!!dev.wuffs.squatgrow.config.SquatGrowConfig
allowAdventureTwerking: false
chance: 0.01
debug: false
enableMysticalCrops: false
ignoreList: ['minecraft:grass_block', 'minecraft:grass', 'minecraft:tall_grass', 'minecraft:netherrack',
  'minecraft:warped_nylium', 'minecraft:crimson_nylium']
range: 1
useWhitelist: false
